### PR TITLE
Initial commit for index, reset, my-personal-grid, stickler and stylelint

### PR DESCRIPTION
**Pull request by kilonzi**
Creating a fully responsive homepage based off a clone of Doist

### CODE REVIEW

**Review by Forison — COMMENTED** [review]
# Pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
### Good job @kilonzi 
I would like to know why you did the project alone. Kindly notify me via my contact info below⬇️
> one has to obtain permission before doing projects alone

The project looks good, nice readme file.

Here are a few changes we have to do to have our project approved
* [x] remove unused file form project
> I see ```sss.css```, ```main.min.css``` which are not being used in the project.
* [x] let us fix the warning returned by the[ validator ](https://validator.w3.org)when uploading the index file.🙂

## Kindly make those changes and submit for review🙂🙂

feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. I would be happy to assist you.

Good luck next time  😇😇😇

**Comment by kilonzi** [comment]
@Forison I have removed unused CSS files and resolved the validator warnings

**Review by stratospherique — APPROVED** [review]
> ### Review by Ahmed Mahfoudh TSE

### Amazing work :clap: . I approve your project and you may merge to master :+1: :+1:

**Pull request merged**
